# Custom Language File for Launcher Customizer

[ejs.app]
title = "TR18S Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/The-Realm-18-Studios-Mods/TR18SLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/czS9Xu4CJY"

[ejs.settings]
sourceGithubLink = "https://github.com/The-Realm-18-Studios-Mods/TR18SLauncher"
supportLink = "https://github.com/The-Realm-18-Studios-Mods/TR18SLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO TACKY TECH TEAM SERVER"
welcomeDescription = "This is a private launcher that will be used to update the content creators of the server.  Only people that have this launcher can join the server."
welcomeDescCTA = "You are just a few clicks away from TTT Server."
